using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;
using static UnityEngine.Rendering.DebugUI;

public interface IRecoveryMP
{
    void RecoveryMP(bool isUsingSkill);
}

// ว๖ภ็ พศพธ
public interface IUsingPotionAct
{
    event UnityAction m_usingPotionAct;
}

public class PlayerUI : MonoBehaviour, IRecoveryMP
{
    //public event UnityAction<float> m_usingPotionAct = null;
    public UnityEvent<float> m_usingPotionAct = null;
    public Player m_player;
    public Image m_hpUI;
    public Image m_mpUI;
    //public Text m_hpText;
    //public Text m_mpText;
    public TextMeshProUGUI m_hpText;
    public TextMeshProUGUI m_mpText;
    public SkillCoolTime m_skillCoolTime;
    public UsingPotion m_potionFlame;

    // Start is called before the first frame update
    void Start()
    {
        Initialize();
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Alpha1))
        {
            if (m_potionFlame.m_potion != null && m_player.m_curHp < m_player.m_stat.MaxHp)
            {
                m_usingPotionAct?.Invoke(m_potionFlame.m_potion.GetComponent<Item>().m_itemData.recoveryAmount);
                IUsePotion iup = m_potionFlame.GetComponent<IUsePotion>();
                if (iup != null)
                {
                    iup.UsePotion();
                }
            }
        }
    }


    // HP MP UI ภฬนฬม๖ 2ฐณทฮ ธธต้พ๎ผญ "{พีฟก ฑืทมม๘ ภฬนฬม๖ดย วัน๘ฟก มูพ๎ต้ฐิ} {ตฺฟก ฑืทมม๘ ภฬนฬม๖ดย Time.deltaTime ฝแผญ ผญผญศ๗ มูพ๎ต้ฐิ ธธต้ฑโ}"
    void Initialize()
    {
        //m_hpText.text = m_player.GetComponent<BattleSystem>().m_stat.MaxHp + " / " + m_player.GetComponent<BattleSystem>().m_stat.MaxHp;
        //m_mpText.text = m_player.GetComponent<BattleSystem>().m_stat.MaxMp + " / " + m_player.GetComponent<BattleSystem>().m_stat.MaxMp;

        m_hpText.text = m_player.GetComponent<BattleSystem>().m_stat.MaxHp + " / " + m_player.GetComponent<BattleSystem>().m_stat.MaxHp;
        m_mpText.text = m_player.GetComponent<BattleSystem>().m_stat.MaxMp + " / " + m_player.GetComponent<BattleSystem>().m_stat.MaxMp;
    }

    // วรทนภฬพ๎ภว รผทยภฬ ศธบน, ฐจผาวิฟก ต๛ถ๓ วิผ๖ ฝววเ
    public void HealthPoint(float value, float MaxHpValue, bool healCheck)
    {
        // รผทย ศธบน UI วิผ๖ ฝววเ
        if (healCheck)
        {
            RecoveryHp(value);
            //m_hpText.text = (value * MaxHpValue).ToString() + " / " + (MaxHpValue).ToString();
            m_hpText.text = (value * MaxHpValue).ToString() + " / " + (MaxHpValue).ToString();
        }
        // รผทย ฐจผา UI วิผ๖ ฝววเ
        else
        {
            StopAllCoroutines();
            StartCoroutine(DamagedHealPoint(value));
            //m_hpText.text = (value * MaxHpValue).ToString() + " / " + (MaxHpValue).ToString();
            m_hpText.text = (value * MaxHpValue).ToString() + " / " + (MaxHpValue).ToString();
        }
    }

    // วรทนภฬพ๎ภว ธถณชฐก ศธบน, ฐจผาวิฟก ต๛ถ๓ วิผ๖ ฝววเ
    public void ManaPoint(float value, float MaxMpValue, bool isUsingSkill)
    {
        // ธถณช ฐจผา UI วิผ๖ ฝววเ
        if (isUsingSkill)
        {
            StopAllCoroutines();
            StartCoroutine(UsingManaPoint(value));
            //m_mpText.text = (value * MaxMpValue).ToString() + " / " + (MaxMpValue).ToString();
            //m_mpText.text = Mathf.FloorToInt(value * MaxMpValue).ToString() + " / " + (MaxMpValue).ToString();
            m_mpText.text = Mathf.FloorToInt(value * MaxMpValue).ToString() + " / " + (MaxMpValue).ToString();
        }
        // ธถณช ศธบน UI วิผ๖ ฝววเ
        else
        {
            RecoveryMP(isUsingSkill);
            //m_mpText.text = (value * MaxMpValue).ToString() + " / " + (MaxMpValue).ToString();
            //m_mpText.text = Mathf.FloorToInt(value * MaxMpValue).ToString() + " / " + (MaxMpValue).ToString();
        }
    }


    #region UI ภฺฟ๘ ฐจผา วิผ๖
    // วรทนภฬพ๎ภว รผทย UI ฐจผา
    IEnumerator DamagedHealPoint(float value)// value : ว๖ภ็ ตฅนฬม๖ธฆ ภิภบ ศฤ วรทนภฬพ๎ภว รผทย || ฝบลณ ป็ฟ๋ ธถณช
    {
        float beforeHp = m_hpUI.fillAmount;
        float hp = m_hpUI.fillAmount - value;
        float val = 0;
        while (val <= hp)
        {
            val += Time.deltaTime * 0.5f;
            m_hpUI.fillAmount = beforeHp - val;
            yield return null;
        }

        m_hpUI.fillAmount = value;
    }

    // วรทนภฬพ๎ ธถณช UI ฐจผา
    IEnumerator UsingManaPoint(float value)
    {
        float beforeMp = m_mpUI.fillAmount;
        float mp = m_mpUI.fillAmount - value;
        float val = 0;
        while (val <= mp)
        {
            val += Time.deltaTime * 0.5f;
            m_mpUI.fillAmount = beforeMp - val;
            yield return null;
        }

        m_mpUI.fillAmount = value;
    }
    #endregion


    #region UI ภฺฟ๘ ศธบน วิผ๖
    // รผทย ศธบน UI
    public void RecoveryHp(float value)
    {
        StopAllCoroutines();
        StartCoroutine(RecoveryHealPoint(value));
    }
    // รผทย ศธบน UI ฤฺท็ฦพ
    IEnumerator RecoveryHealPoint(float value)
    {
        while (!Mathf.Approximately(m_hpUI.fillAmount, value))
        {
            m_hpUI.fillAmount = Mathf.Lerp(m_hpUI.fillAmount, value, Time.deltaTime * 2);
            yield return null;
        }
        m_hpUI.fillAmount = value;
    }


    // ธถณช ศธบน UI
    public void RecoveryMP(bool isUsingSkill)
    {
        // รผทย ศธบน นฎมฆภึภธธ้ StopCoroutine(RecoveryManaPoint(isUsingSkill)); ทฮ นูฒูฑโ
        StopAllCoroutines();
        StartCoroutine(RecoveryManaPoint(isUsingSkill));
    }

    // ธถณช ศธบน UI ฤฺท็ฦพ
    IEnumerator RecoveryManaPoint(bool isUsingSkill)
    {
        while (!isUsingSkill && m_mpUI.fillAmount < 1)
        {
            m_mpUI.fillAmount += Time.deltaTime * 0.1f;
            //m_mpText.text = Mathf.FloorToInt(m_mpUI.fillAmount * m_player.m_stat.MaxMp).ToString() + " / " + (m_player.m_stat.MaxMp).ToString();
            m_mpText.text = Mathf.FloorToInt(m_mpUI.fillAmount * m_player.m_stat.MaxMp).ToString() + " / " + (m_player.m_stat.MaxMp).ToString();
            yield return null;
        }
        if (m_mpUI.fillAmount >= 1)
        {
            m_mpUI.fillAmount = 1;
            //m_mpText.text = Mathf.FloorToInt(m_mpUI.fillAmount * m_player.m_stat.MaxMp).ToString() + " / " + (m_player.m_stat.MaxMp).ToString();
            m_mpText.text = Mathf.FloorToInt(m_mpUI.fillAmount * m_player.m_stat.MaxMp).ToString() + " / " + (m_player.m_stat.MaxMp).ToString();
        }
    }
    #endregion
}
