using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
public interface IEquipItemStatUI
{
    void EquipItemStat(ItemData itemData);
}

public interface IUnEquipItemStatUI
{
    void UnequipItemStat(ItemData itemData);
}

public interface IAdditionalStats
{
    Dictionary<string, float> AdditionalStats { get; set; }
}

public class PlayerStatUI : MonoBehaviour, IEquipItemStatUI, IUnEquipItemStatUI, IAdditionalStats
{
    [SerializeField]
    private Player s_player;
    [SerializeField]
    private GameObject statsPanel;   // НКХШ UI ЦаГЮ ПРКъСЇЦЎ
    [SerializeField]
    private TextMeshProUGUI healthText;
    [SerializeField]
    private TextMeshProUGUI manaText;
    [SerializeField]
    private TextMeshProUGUI attackDmgText;
    [SerializeField]
    private TextMeshProUGUI defenseText;
    // ПЉЗЏ ОЦРЬХлРЛ АќИЎЧЯДТ ИЎНКЦЎ
    [SerializeField]
    private List<ItemData> itemDataList;

    private bool isStatsVisible = false;  // НКХШУЂ ЧЅНУ ПЉКЮ
    private bool hasEquippedItem = false; // ОЦРЬХл РхТј ПЉКЮ

    // РхТј ОЦРЬХлРИЗЮ СѕАЁЧб НКХШРЛ ЕћЗЮ РњРх
    private float additionalAttackDmg = 0.0f;
    private float additionalDefense = 0.0f;

    // AdditionalStats РЮХЭЦфРЬНК БИЧі
    public Dictionary<string, float> AdditionalStats { get; set; } = new Dictionary<string, float>();

    // УЪБт НКХГ ЕЅЙЬСі РњРх
    private Dictionary<string, float> initialSkillDmgDict = new Dictionary<string, float>();


    // УЪБт НКХШ РњРх
    private float initialhealth;
    private float initialmana;
    private float initialAttackDmg;
    private float initialDefense;
    private float[] initialSkillDmg;

    // ЛіЛѓ СЄРЧ
    private Color normalColor = Color.white;  // БтКЛ ЛіЛѓ
    private Color increaseColor = Color.yellow;  // СѕАЁ НУ ГыЖѕЛі
    

    void Awake()
    {
        // ЧУЗЙРЬОюРЧ УЪБт НКХШ РњРх
        initialAttackDmg = s_player.m_stat.AttackDmg;
        initialDefense = s_player.m_stat.Defense;

        // SkillDataManagerПЁМ­ НКХГ ЕЅРЬХЭИІ АЁСЎПЭМ­ ЙшП­ЗЮ МГСЄ
        int skillCount = SkillDataManager.m_skillDataDic.Count;
        initialSkillDmg = new float[skillCount];



        UpdateStatUI();
    }

    public void UpdateStatUI()
    {
        if (s_player != null)
        {  // БтКЛ НКХШРК ЧзЛѓ ЧЅНУ
            healthText.text = $"{s_player.m_stat.MaxHp}";
            manaText.text = $"{s_player.m_stat.MaxMp}";

            // АјАнЗТАњ ЙцОюЗТРК БтКЛАЊ + УпАЁАЊРИЗЮ ЧЅНУ (ОЦРЬХл РхТј ЛѓХТПЁ ЕћЖѓ ЛіЛѓ КЏАц)
            if (hasEquippedItem)
            {
                if (additionalAttackDmg > 0)
                {
                    attackDmgText.color = increaseColor;  // ГыЖѕЛі
                    attackDmgText.text = $"{s_player.m_stat.AttackDmg} (+{CalculateStat(initialAttackDmg, additionalAttackDmg, true)})";
                }
                else
                {
                    attackDmgText.color = normalColor;  // БтКЛЛі
                    attackDmgText.text = $"{s_player.m_stat.AttackDmg}";
                }

                if (additionalDefense > 0)
                {
                    defenseText.color = increaseColor;  // ГыЖѕЛі
                    defenseText.text = $"{s_player.m_stat.Defense} (+{CalculateStat(initialDefense,additionalDefense, false)})";
                }
                else
                {
                    defenseText.color = normalColor;  // БтКЛЛі
                    defenseText.text = $"{s_player.m_stat.Defense}";
                }
            }
            else
            {
                // РхТј ОЦРЬХлРЬ ОјРЛ АцПь БтКЛ ЛіЛѓРИЗЮ НКХШИИ ЧЅНУ
                attackDmgText.color = normalColor;
                attackDmgText.text = $"{s_player.m_stat.AttackDmg}";

                defenseText.color = normalColor;
                defenseText.text = $"{s_player.m_stat.Defense}";
            }
        }
    }

    // СѕАЁ(АЈМв)РВ
    float CalculateStat(float initStat, float addStat, bool isAtk)
    {
        if (isAtk)
        {
            return initStat * (addStat * 0.01f);
        }
        else
        {
            return addStat * 0.01f;
        }
    }

    // УжСОАЊ
    float CalculateFinalStat(float initStat, float addStat, bool isAtk)
    {
        return initStat + CalculateStat(initStat, addStat, isAtk);
    }

    void ChangeStat()
    {
        s_player.m_stat.AttackDmg = CalculateFinalStat(initialAttackDmg, additionalAttackDmg, true);
        s_player.m_stat.Defense = CalculateFinalStat(initialDefense, additionalDefense, false);

        SkillDataManager.m_skillDataDic["Warpath"].Dmg = CalculateFinalStat(SkillDataManager.m_skillDataDic["Warpath"].InitDmg, additionalAttackDmg, true);
        SkillDataManager.m_skillDataDic["ErasingStrike"].Dmg = CalculateFinalStat(SkillDataManager.m_skillDataDic["ErasingStrike"].InitDmg, additionalAttackDmg, true);
        SkillDataManager.m_skillDataDic["Lunge"].Dmg = CalculateFinalStat(SkillDataManager.m_skillDataDic["Lunge"].InitDmg, additionalAttackDmg, true);
    }

    // РгНУЗЮ ОЦРЬХл РхТј ШФ НКХШ СѕАЁНУХАДТ ЧдМі
    public void EquipItemStat(ItemData itemData)
    {
        if (itemData != null && s_player != null)
        {
          
            // additional АЊРК УжСО АшЛъЕШ АЊ
            additionalAttackDmg += itemData.atkPower;
            additionalDefense += itemData.defense;

    
            ChangeStat();

            // ОЦРЬХлРЬ РхТјЕЧОњДйДТ МГСЄ
            hasEquippedItem = true;

            // РхТј ШФ НКХШ UI ОїЕЅРЬЦЎ
            UpdateStatUI();
        }
    }

    // ОЦРЬХл ЧиСІ НУ НКХШРЛ ДйНУ АЈМвНУХАДТ ЧдМі
    public void UnequipItemStat(ItemData itemData)
    {
        if (itemData != null && s_player != null && hasEquippedItem)
        {
            // РхТј ЧиСІ НУ УпАЁЕШ НКХШРЛ АЈМв
            additionalAttackDmg -= itemData.atkPower;
            additionalDefense -= itemData.defense;


            ChangeStat();

            // УпАЁ НКХШРЬ И№ЕЮ ЧиСІЕЧИщ РхТј ЛѓХТ ЧиСІ
            if (additionalAttackDmg <= 0 && additionalDefense <= 0)
            {
                hasEquippedItem = false;
            }

            // ЧиСІ ШФ НКХШ UI ОїЕЅРЬЦЎ
            UpdateStatUI();
        }
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Z))
        {
            if (!isStatsVisible)
            {
                statsPanel.SetActive(true);
            }
            else
            {
                statsPanel.SetActive(false);
            }
            isStatsVisible = !isStatsVisible;
        }

        // РгНУЗЮ 1Йј ОЦРЬХлРЛ РхТјЧЯДТ ПЙНУ
        if (Input.GetKeyDown(KeyCode.F1))
        {
            if (itemDataList.Count > 0)
            {
                EquipItemStat(itemDataList[0]);  // УЙ ЙјТА ОЦРЬХл РхТј
            }
        }

        // РгНУЗЮ 2Йј ОЦРЬХлРЛ РхТјЧЯДТ ПЙНУ 
        if (Input.GetKeyDown(KeyCode.F2))
        {
            if (itemDataList.Count > 1)
            {
                EquipItemStat(itemDataList[1]);  // ЕЮ ЙјТА ОЦРЬХл РхТј
            }
        }

        // РгНУЗЮ 1Йј ОЦРЬХлРЛ ЧиСІЧЯДТ ПЙНУ 
        if (Input.GetKeyDown(KeyCode.F3))
        {
            if (itemDataList.Count > 0)
            {
                UnequipItemStat(itemDataList[0]);  // УЙ ЙјТА ОЦРЬХл ЧиСІ
            }
        }

        // РгНУЗЮ 2Йј ОЦРЬХлРЛ ЧиСІЧЯДТ ПЙНУ 
        if (Input.GetKeyDown(KeyCode.F4))
        {
            if (itemDataList.Count > 1)
            {
                UnequipItemStat(itemDataList[1]);  // ЕЮ ЙјТА ОЦРЬХл ЧиСІ
            }
        }



    }

 
}